<?php
// Assets de l'application
$this->assets()
    ->finalize();

// Titre de l'application
$this->title();
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?= $this->headTitle() . "\n"?>

        <?= $this->headLink() . "\n" ?>
        <?= $this->headStyle() . "\n" ?>
        <?= $this->headScript() . "\n" ?>
        <?= $this->inlineScript() . "\n" ?>

        <link href="<?= $this->assets()->file('oft/img/favicon.ico') ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
    </head>
    <body role="document">

        <header>
            <?= $this->widget('menuBar'); ?>
        </header>

        <main class="container">
            <?php if (count($this->breadcrumb())) { ?>
                <?= $this->breadcrumb() ?>
            <?php } ?>

            <?= $this->flashMessenger() ?>

            <?= $this->content ?>
        </main>

        <?= $this->footer(); ?>
        <?= $this->debugBar(); ?>

    </body>
</html>
