<?php
$this->assets()
    ->finalize();
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?= $this->headLink() . "\n" ?>
        <?= $this->headStyle() . "\n" ?>

        <?= $this->headTitle() . "\n" ?>
        
        <link href="<?= $this->assets()->file('oft/img/favicon.ico') ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
    </head>
    <body role="document">

        <!-- Contenu -->
        <main class="container">
            <?= $this->content ?>
        </main>

    </body>
</html>
